<?php

return [
        'APP_URL' => env('APP_URL'),
        'APP_NAME' => env('APP_NAME'),
        'MAIL_FROM_ADDRESS' => env('MAIL_FROM_ADDRESS'),

        'DEFAULT_ADMIN_NAME' => env('DEFAULT_ADMIN_NAME'),
        'DEFAULT_ADMIN_EMAIL' => env('DEFAULT_ADMIN_EMAIL'),
        'DEFAULT_ADMIN_PASSWORD' => env('DEFAULT_ADMIN_PASSWORD'),
        'DEFAULT_ADMIN_CODE' => env('DEFAULT_ADMIN_CODE'),
        'DEFAULT_ADMIN_PHONE' => env('DEFAULT_ADMIN_PHONE'),
        'DEFAULT_ADMIN_PHONE_VERIFIED' => env('DEFAULT_ADMIN_PHONE_VERIFIED'),

        'DB_DATABASE' => env('DB_DATABASE'),
        'DB_DATABASE_2' => env('DB_DATABASE_2'),
        'WINWASTE_DB' => env('WINWASTE_DB'),

        'FACEBOOK_CLIENT_ID' => env('FACEBOOK_CLIENT_ID'),
        'FACEBOOK_CLIENT_SECRET' => env('FACEBOOK_CLIENT_SECRET'),
        'FACEBOOK_URL' => env('FACEBOOK_URL'),

        'GOOGLE_CLIENT_ID' => env('GOOGLE_CLIENT_ID'),
        'GOOGLE_CLIENT_SECRET' => env('GOOGLE_CLIENT_SECRET'),
        'GOOGLE_URL' => env('GOOGLE_URL'),

        'MAX_INVITATION_SENDINGS' => env('MAX_INVITATION_SENDINGS'),

        'SMS_FROM' => env('SMS_FROM'),
        'SMS_GATEWAY_APIKEY' => env('SMS_GATEWAY_APIKEY'),
        'SMS_OTP_MAX_SEND' => env('SMS_OTP_MAX_SEND'),

        'STRIPE_KEY' => env('STRIPE_KEY'),
        'STRIPE_SECRET' => env('STRIPE_SECRET'),

        'FILESYSTEM_DRIVER' => env('FILESYSTEM_DRIVER'),

        'PAYPAL_MODE' => env('PAYPAL_MODE'),
        'PAYPAL_SANDBOX_API_USERNAME' => env('PAYPAL_SANDBOX_API_USERNAME'),
        'PAYPAL_SANDBOX_API_PASSWORD' => env('PAYPAL_SANDBOX_API_PASSWORD'),
        'PAYPAL_SANDBOX_API_SECRET' => env('PAYPAL_SANDBOX_API_SECRET'),
        'PAYPAL_CURRENCY' => env('PAYPAL_CURRENCY'),
        'PAYPAL_SANDBOX_API_CERTIFICATE' => env('PAYPAL_SANDBOX_API_CERTIFICATE'),

        'BRAINTREE_ENVIRONMENT' => env('BRAINTREE_ENVIRONMENT'),
        'BRAINTREE_MERCHANT_ID' => env('BRAINTREE_MERCHANT_ID'),
        'BRAINTREE_PUBLIC_KEY' => env('BRAINTREE_PUBLIC_KEY'),
        'BRAINTREE_PRIVATE_KEY' => env('BRAINTREE_PRIVATE_KEY'),

        'USER_PROFILE_COMPLETE' => env('USER_PROFILE_COMPLETE'),
        'USER_PHONE_VERIFY' => env('USER_PHONE_VERIFY'),

        'ASSET_COLOR' => env('ASSET_COLOR'),

        'MACHINE_INFO_CRON_TIME_MINUTES' => env('MACHINE_INFO_CRON_TIME_MINUTES'),
        'MACHINE_INFO_REFRESH_TIME_MINUTES' => env('MACHINE_INFO_REFRESH_TIME_MINUTES'),
        'MACHINE_TELEMETRY_CRON_TIME_MINUTES' => env('MACHINE_TELEMETRY_CRON_TIME_MINUTES'),
        'MACHINE_TELEMETRY_REFRESH_TIME_MINUTES' => env('MACHINE_TELEMETRY_REFRESH_TIME_MINUTES'),

        'EMAIL_ALERT_MANTEINANCE' => env('EMAIL_ALERT_MANTEINANCE'),
        'DAYS_ALERT_MANTEINANCE' => env('DAYS_ALERT_MANTEINANCE'),

        'OPC_HOST' => env('OPC_HOST'),

];
